#
# role python-build
# tasks file
#

- name: Stop unattended upgrades
  systemd:
    name: unattended-upgrades
    state: stopped
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    
- name: Purge unattended-upgrades
  apt:
    name: unattended-upgrades
    purge: yes
  when:
    - ansible_facts['distribution'] == 'Ubuntu'

- name: Install Ubuntu packages for python3
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - python3-boto3
      - python3-botocore
  when:
    - ansible_facts['distribution'] == 'Ubuntu'

- name: Install CentOS packages for python3
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - python3
      - python3-pip
  when:
    - ansible_facts['distribution'] == 'CentOS'  

- name: create the lib directory
  file:
    state: directory
    path: "/opt/management/lib/litfibre-common"
    mode: "0755"
    recurse: yes

- name: create the bin directory
  file:
    state: directory
    path: "/opt/management/bin"
    mode: "0755"

- name: copy in the python-commons library
  copy:
    src: litfibre-common/
    dest: /opt/management/lib/litfibre-common/

- name: Install the litfibre-common library
  shell:
    cmd: python3 setup.py install
    chdir: /opt/management/lib/litfibre-common/

- name: Install pip packages
  pip:
    name:
      - psutil
      - iso8601